### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by skleinfeldt** [PSUEducationalEquity/plonetheme.eeq#7]
As a user I can see a themed header throughout the site, with the main nav based on the top level folder structure. (This story covers the top 2 bands and stops at the hero image.)

**Comment by alecpm** [comment]
@silviot I merged the branch as is because it's a big improvement, but this still needs a couple small things.

* The logo should like to the site base url
* The Report Bias and Give Now links should link to internal site pages (probably placeholder aliases like `$site_url//report-bias` and `$site_url//donate`)
* The Contact button should be linked to `$site_url/contact-info` with `class="pat-plone-modal"` and `data-pat-plone-modal="{}"`. Maybe that link can just be extracted from the site actions and then dropped from the content in the rules file?

**Comment by paulrentschler** [comment]
* The Report Bias link should point to an existing folder in the root with ID `report-bias`
* The Give Now link should point to an existing document in the root with ID `giving`

**Comment by silviot** [comment]
@MBrahosky @paulrentschler `master` now has fixes for the footer and the header.

**Comment by silviot** [comment]
The links that use `portal_url` are not working properly: _Contact_, _Report Bias_, _Give now_ do not include the `/web` part on https://beta.equity.psu.edu/web

**Comment by paulrentschler** [comment]
The top navigation does not appear to be working right for small screen devices. When I click the hamburger button, the menu slides down and then instantly disappears. When I click it again, it appears and slides up.

**Comment by alecpm** [comment]
I just pushed an update that includes a custom compile of the Plone JS bundle without bootstrap 3 JS components. Locally it appears to have fixed the mobile navigation issue.

You'll need to run buildout and restart the instances. There should be an upgrade step in the add-ons control panel, though I don't think it's necessary to see the fix, but you might need to clear your browser cache. 

There is also a script for generating and installing a new plone JS bundle override that can be run when the base Plone JS changes.

**Comment by skleinfeldt** [comment]
@silviot the search button is misplaced on my desktop view, it's underneath the query box instead of to the side. Also it should be blue per https://beta.equity.psu.edu/a51/develop/office-home.html.

I'm on Firefox on MacOS.

**Comment by silviot** [comment]
@paulrentschler The header buttons are now fixed in `master` and deployable.

**Comment by paulrentschler** [comment]
@silviot the header buttons look good now.

@alecpm the mobile hamburger menu is still not working right. I've deployed, restarted the clients, run all the upgrade steps, even toggled the theme to a different one and back. It is not working on Firefox, Chrome, and Edge on Windows 10 as well as Firefox, Chrome, and Safari on iPhone iOS.

**Comment by alecpm** [comment]
@paulrentschler It looks like the simple buildout run/upgrade step wasn't sufficient to rebuild the JS. I did it manually in the resource registry controlpanel and it seems to be working now. I'm going to take a quick look to see why the override I added didn't work with a simple upgrade step.

**Comment by alecpm** [comment]
@paulrentschler I've fixed the underlying issue related to the JS overrides, so let me know when the next deploy is completed and I'll undo the TTW customization.

**Comment by paulrentschler** [comment]
@alecpm code has been deployed.

**Comment by paulrentschler** [comment]
One remaining issue with the responsive menu; at a device width of 768px the hero image is displayed and should be hidden when the menu is expanded, then displayed again when the menu is closed. This took a little work to make function correctly in the mockup code, but a working example is there. I think I added custom Bootstrap event handlers to slide the hero image up and down.

**Comment by alecpm** [comment]
@paulrentschler That seems like something we should tackle once we have clearer guidance on the hero images via story #11. Doesn't sound too tricky, but I worry a bit we'll end up needing to implementing it twice.

**Comment by paulrentschler** [comment]
@alecpm that sounds like a plan.
